server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy para a API se necessário (opcional, mas recomendado se quiser evitar problemas de CORS no Nginx)
    # location /v1/ {
    #     proxy_pass http://backend:3000/v1/;
    # }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
